# This is an example file with development values. You should copy
# this file into a new file called "secrets.yaml" in the k8s folder.
# You can change the values to match your environment if needed.

apiVersion: v1
kind: Secret
metadata:
  name: catima-secrets
type: Opaque
data:
  POSTGRES_USER: dXNlcg== # user
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # password
