# This is an example file with development values. You should copy
# this file into a new file called "configmap.yaml" in the k8s folder.
# You can change the values to match your environment if needed.

apiVersion: v1
kind: ConfigMap
metadata:
  name: catima-config
data:
  RAILS_ENV: development
  REDIS_HOST: catima-redis
  REDIS_PORT: "6379"
  POSTGRES_HOST: catima-postgres
  POSTGRES_PORT: "5432"
  MAIL_SMTP_ADDRESS: catima-mailhog
  MAIL_SMTP_PORT: "1025"
  ASSET_HOST: http://catima.lan:8383
  DOMAIN: catima.lan:8383
  PROTOCOL: http
