apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: app-data
  name: app-data
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
