apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    io.kompose.service: catima-app
  name: catima-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: catima-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      labels:
        io.kompose.service: catima-app
    spec:
      initContainers:
        - image: alpine/git
          name: git-cloner
          command:
            - git
            - clone
            - --branch
            - master
            - https://github.com/shamimice03/demo-init-container.git
            - /var/www/catima
      containers:
        - image: unillett/catima:latest-app
          name: catima-app
          envFrom:
            - configMapRef:
              name: catima-config
            - secretRef:
              name: catima-secrets
          ports:
            - containerPort: 3000
          resources: {}
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 600
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - mountPath: /var/www/catima
              name: app-data
      restartPolicy: Always
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: app-data
status: {}
