apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (HEAD)
  labels:
    io.kompose.service: catima-worker
  name: catima-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: catima-worker
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (HEAD)
      labels:
        io.kompose.network/app-catima-net: "true"
        io.kompose.service: catima-worker
    spec:
      initContainers:
        - name: wait-for-app
          image: atkrad/wait4x:latest
          command:
            - wait4x
            - http
            - http://catima-app:8383/health
            - --expect-status-code
            - "200"
      containers:
        - image: unillett/catima:latest-worker
          name: catima-worker
          envFrom:
            - configMapRef:
              name: catima-config
            - secretRef:
              name: catima-secrets
          resources: {}
          volumeMounts:
            - mountPath: /var/www/catima
              name: app-data
      restartPolicy: Always
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: app-data
status: {}
