apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app-catima-net
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              io.kompose.network/app-catima-net: "true"
  podSelector:
    matchLabels:
      io.kompose.network/app-catima-net: "true"
