name: k8s
on: [push, pull_request]
jobs:
  build:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Manifests validation
        uses: yokawasa/action-setup-kube-tools@v0.9.2
        with:
          setup-tools: |
            kubeconform
      - run: kubeconform -summary k8s

  notification:
    name: Notify
    runs-on: ubuntu-latest
    needs: build
    if: always()
    continue-on-error: true

    steps:
      - uses: technote-space/workflow-conclusion-action@v3
      - uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.TEAMS_CI_WEBHOOK_URL }}
          deploy-card: true
          timezone: "Europe/Zurich"
          title: ${{ env.WORKFLOW_CONCLUSION }} (k8s)
          color: ${{ env.WORKFLOW_CONCLUSION }}
